"""Stable defaults for the BioHub cell-tracking pipeline."""

DEFAULT_VOXEL_SIZE_UM = (1.625, 0.40625, 0.40625)
DEFAULT_ANISOTROPY = DEFAULT_VOXEL_SIZE_UM[0] / DEFAULT_VOXEL_SIZE_UM[1]
MATCH_DISTANCE_UM = 7.0
DIVISION_SCORE_WEIGHT = 0.1
